Catalog 2  -  3
lilkxst/iOS-FakeNFT-StarterProject-Public pull request #14
Opened 2023-12-28 14:55 UTC by NikolayDolnik

выбранная командой архитектура и способ верстки - MVP и полностью кодом
декомпозиция эпика (ссылка на таск-трекер) - https://github.com/users/lilkxst/projects/8
декомпозиция эпика (приложенный текстовый документ .md) - https://github.com/lilkxst/iOS-FakeNFT-StarterProject-Public/blob/common/docs/Catalog.md
первоначальная оценка времени выполнения задач - 290
реальное время, потраченное на решении каждой задачи - 720

2023-12-28 15:24 UTC, bukhmillerEd commented on FakeNFT/Scenes /Catalog/CatalogController.swift
> +        self.init(servicesAssembly: servicesAssembly, presenter: CatalogPresenter(service: servicesAssembly.nftCatalogService))
Поделюсь что мне на предыдущем ревью подсказали :
Там где ты презентуешь контроллер сначала создаешь презентер - 
        let presenter = CatalogPresenter(servicesAssembly: servicesAssembly)
а потом создаешь контроллер и передаешь в него презентер
        let vc = CatalogViewController:(presenter: presenter)
Так у этих классов сводится к минимум зависимость друг от друга

2023-12-28 15:28 UTC, bukhmillerEd commented on FakeNFT/Scenes /Catalog/CollectionNFT/CollectionNFT.swift
>          let sv = UIStackView()
На одном из ревью мне рекомендовали не сокращать слова, то есть или stack или stackView

2023-12-29 15:37 UTC, protos17 requested changes

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Foundation/MemoryStorage/CatalogStorage.swift
> +        }
Здесь удобнее будет написать:

      likes.first(where: { $0 == id })

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Foundation/MemoryStorage/CatalogStorage.swift
> +                self?.orders.insert(nft)
Лишние отступы, рекомендую нажать control + i

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogController.swift
> +       let vc = CollectionNFTViewController(
Рекомендую давать более информативные названия для констант, в этом месте даже swiftlint ругается на длину названия константы:
[Статья додо: Делай нейминг как сеньор][(https://habr.com/ru/companies/dododev/articles/714512/](https://habr.com/ru/companies/dododev/articles/714512/))

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +        service.loadNft( completion: { result in
Сильная ссылка

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +                print(error)
Рекомендую показывать алерт с ошибкой, чтобы пользователю было понятно, почему приложение не работает

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CollectionNFT/CollectionNFT.swift
> +protocol NftCollectionView: AnyObject {
Протокол не должен иметь в названии View - такое название должно быть только у вьюшек

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CollectionNFT/CollectionNFT.swift
> +    let stackViewDescriptionLabel: UIStackView = {
Здесь рекомендую указать как private

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CollectionNFT/CollectionNFT.swift
> +    convenience init(servicesAssembly: ServicesAssembly, collection: NFTCollection?){
Рекомендую оставить только основной инициализатор, в него же передать уже созданный presenter, потому что ты все равно используешь только один инициализатор для создания и создание презентера внутри данного вью-контроллера нарушает принцип единой ответственности

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CollectionNFT/CollectionNFT.swift
> +    func didTapAuthor(){
Рекомендую сразу указывать как приватный метод

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CollectionNFT/CollectionNFTPresenter.swift
> +            url: URL(string: nft.images[0])!
Не рекомендую обращаться к элементу массива по индексу, здесь лучше заменить на nft.images.first или сначала добавить проверку, что массив не пустой, иначе приложение вылетит

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CollectionNFT/CollectionNFTPresenter.swift
> +        let name = (names?[0] ?? "") + " " + (names?[1] ?? "")
Здесь тоже рекомендую избавиться от обращения по индексу, лучше добавить пробегание по массиву, потому что если не будет значений, приложение вылетит:

     func convertAuthor() -> String {
        var authorName = ""
        guard let names = collection?.author.components(separatedBy: "_").prefix(2) else {
            return authorName
        }
        for name in names {
            authorName += " \(name)"
        }
        return authorName.capitalized
    }

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/Сell/CollectionNFTCell.swift
> +    func didTapLike(){
Рекомендую указать как private

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/Сell/CollectionNFTCell.swift
> +    func didTapBasket(){
Также рекомендую указать как private

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Scenes /Catalog/Сell/NftCellDelegateProtocol.swift
> +public protocol NftCellDelegate {
Рекомендую убрать public везде в проекте, потому что мы работаем в пределах одного проекта и области видимости internal здесь достаточно, которую мы не пишем:
[Статья про модификаторы доступа](https://sparrowcode.io/ru/tutorials/access-control)

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Services/NFTCatalogService.swift
> +        loadOrders { _ in }
Рекомендую убрать их отсюда, потому что запрос все равно идет снаружи

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Services/NFTCatalogService.swift
> +       storage.getNft(with: id) == nil ? false : true
Здесь рекомендую заменить на:

      storage.getNft(with: id) != nil

2023-12-29 15:37 UTC, protos17 commented on FakeNFT/Services/Requests/RequestConstants.swift
>      #warning("insert your baseUrl <id>.mockapi.io")
Этот ворнинг рекомендую убрать, чтобы не мешал

2023-12-30 07:46 UTC, NikolayDolnik commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +                print(error)
Обработку ошибок оставил на 3 модуль

2023-12-30 07:51 UTC, NikolayDolnik commented on FakeNFT/Services/NFTCatalogService.swift
> +        loadOrders { _ in }
Хотел сделать предзагрузки профиля и заказа - для отображения ячеек на экране коллекции. Что бы не приходилось ждать запросов при показе картинки лайков и корзины у ячеек. Потому как запросы выполняются не быстро

2024-01-06 15:34 UTC, protos17 approved these changes

2024-01-06 15:34 UTC, protos17 commented on FakeNFT/Foundation/RatingView.swift
>              view.translatesAutoresizingMaskIntoConstraints = false
Тут ты никаких констрейнтов для  UIImageView() не устанавливаешь, поэтому, можно просто удалить

2024-01-06 15:34 UTC, protos17 commented on FakeNFT/Foundation/RatingView.swift
> +
Этот метод можно просто заменить на:

             starsStacView.arrangedSubviews.forEach {
                  starsStacView.removeArrangedSubview($0)
              }

2024-01-06 15:34 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CollectionNFT/CollectionNFTPresenter.swift
> +        let size = Double( 490 + lineSize)
Не совсем понятно, что обозначают эти числа

2024-01-06 17:21 UTC, merged